INSERT INTO geneset VALUES ('5324', 'wit again d', 'primary');
INSERT INTO geneset VALUES ('57', 'tears claim fated', 'primary');
INSERT INTO geneset VALUES ('270', 'fighting toe bui', 'primary');
INSERT INTO geneset VALUES ('1074', 'virtue tax masterly n', 'primary');
INSERT INTO geneset VALUES ('4787', 'cli', 'primary');
INSERT INTO geneset VALUES ('3888', 'show add college tuft r', 'primary');
INSERT INTO geneset VALUES ('4709', 'limits thanks', 'primary');
INSERT INTO geneset VALUES ('1552', 'reignier woman ea', 'primary');
INSERT INTO geneset VALUES ('1932', 'cage name rem', 'primary');
INSERT INTO geneset VALUES ('4620', 'looks', 'primary');
INSERT INTO geneset VALUES ('65', 'prai', 'primary');
INSERT INTO geneset VALUES ('2770', 'sense love', 'primary');
INSERT INTO geneset VALUES ('1395', 'dr', 'primary');
INSERT INTO geneset VALUES ('490', 'equal moans feast', 'primary');
INSERT INTO geneset VALUES ('4089', 'preventions l', 'primary');
INSERT INTO geneset VALUES ('1442', 'fare upo', 'primary');
INSERT INTO geneset VALUES ('4180', 'proculei', 'primary');
INSERT INTO geneset VALUES ('925', 'heir manners gain', 'primary');
INSERT INTO geneset VALUES ('334', 'oxford like boldly', 'primary');
INSERT INTO geneset VALUES ('2645', 'season disposition tie', 'primary');
INSERT INTO geneset VALUES ('3386', 'ratcliff reserva', 'primary');
INSERT INTO geneset VALUES ('1963', 'little master aid', 'primary');
INSERT INTO geneset VALUES ('2179', 'text unhallowed strew', 'primary');
INSERT INTO geneset VALUES ('4187', 'kingdom ca', 'primary');
INSERT INTO geneset VALUES ('1022', 'join him enlarge j', 'primary');
INSERT INTO geneset VALUES ('1572', 'f', 'primary');
INSERT INTO geneset VALUES ('3604', 'scruple beas', 'primary');
INSERT INTO geneset VALUES ('3628', 'know polonius grecian', 'primary');
INSERT INTO geneset VALUES ('949', 'among unnat', 'primary');
INSERT INTO geneset VALUES ('3866', 'sentence resemble', 'primary');
INSERT INTO geneset VALUES ('4167', 'cordia', 'primary');
INSERT INTO geneset VALUES ('1117', 'saw nose scald en', 'primary');
INSERT INTO geneset VALUES ('1785', 'seen cour', 'primary');
INSERT INTO geneset VALUES ('757', 'their reason royal enf', 'primary');
INSERT INTO geneset VALUES ('1934', 'whether woman french', 'primary');
INSERT INTO geneset VALUES ('3905', 'majesty i', 'primary');
INSERT INTO geneset VALUES ('2116', 'valiant reve', 'primary');
INSERT INTO geneset VALUES ('2383', 'prevent', 'primary');
INSERT INTO geneset VALUES ('1567', 'peer going grief falsel', 'primary');
INSERT INTO geneset VALUES ('3161', 'drum death hunt attorne', 'primary');
INSERT INTO geneset VALUES ('2292', 'laughing quittance gone', 'primary');
INSERT INTO geneset VALUES ('4506', 'weather knig', 'primary');
INSERT INTO geneset VALUES ('677', 'sense place wear friend', 'primary');
INSERT INTO geneset VALUES ('1884', 'beneath m', 'primary');
INSERT INTO geneset VALUES ('5336', 'mou', 'primary');
INSERT INTO geneset VALUES ('2015', 'thank capt possible enfo', 'primary');
INSERT INTO geneset VALUES ('2757', 'churlish', 'primary');
INSERT INTO geneset VALUES ('4112', 'wa', 'primary');
INSERT INTO geneset VALUES ('5035', 'naked modo tre', 'primary');
INSERT INTO geneset VALUES ('2803', 'wronged', 'primary');

INSERT INTO synonymset VALUES ('m', '166');
INSERT INTO synonymset VALUES ('shoes tow smile he', '4276');
INSERT INTO synonymset VALUES ('pale', '1370');
INSERT INTO synonymset VALUES ('e', '5495');
INSERT INTO synonymset VALUES ('sciatica knots obs', '2292');
INSERT INTO synonymset VALUES ('gap perform standing ro', '1463');
INSERT INTO synonymset VALUES ('into', '4294');
INSERT INTO synonymset VALUES ('abbeys made opinion se', '415');
INSERT INTO synonymset VALUES ('words heavenly dis', '2500');
INSERT INTO synonymset VALUES ('accents bribe deep hig', '118');
INSERT INTO synonymset VALUES ('cor', '223');
INSERT INTO synonymset VALUES ('pulpit into whip guides', '4112');
INSERT INTO synonymset VALUES ('immediacy forgot s', '4601');
INSERT INTO synonymset VALUES ('crave wage gage em', '3328');
INSERT INTO synonymset VALUES ('chains weak wast ro', '2383');
INSERT INTO synonymset VALUES ('imitate down', '331');
INSERT INTO synonymset VALUES ('grovelling form ra', '5402');
INSERT INTO synonymset VALUES ('pi', '4619');
INSERT INTO synonymset VALUES ('cozen diomed delights', '1843');
INSERT INTO synonymset VALUES ('humours jest rightly eva', '3322');
INSERT INTO synonymset VALUES ('actual food separati', '758');
INSERT INTO synonymset VALUES ('rashly just wherever de', '5024');
INSERT INTO synonymset VALUES ('such sword bolingbrok', '2214');
INSERT INTO synonymset VALUES ('ever ca', '1861');
INSERT INTO synonymset VALUES ('wit falstaff re', '407');
INSERT INTO synonymset VALUES ('slumber', '1448');
INSERT INTO synonymset VALUES ('married groans', '2231');
INSERT INTO synonymset VALUES ('hor s', '2467');
INSERT INTO synonymset VALUES ('bitter vine stood ma', '2558');
INSERT INTO synonymset VALUES ('noblenes', '3286');
INSERT INTO synonymset VALUES ('danc open beguile cri', '741');
INSERT INTO synonymset VALUES ('york desert', '4619');
INSERT INTO synonymset VALUES ('aeneas h', '4254');
INSERT INTO synonymset VALUES ('return beams unknown', '2383');
INSERT INTO synonymset VALUES ('infinit', '3502');
INSERT INTO synonymset VALUES ('ere preventions', '4661');
INSERT INTO synonymset VALUES ('verse sum lament', '5363');
INSERT INTO synonymset VALUES ('sword serpents', '2383');
INSERT INTO synonymset VALUES ('assist', '4589');
INSERT INTO synonymset VALUES ('thank iron duller nigh', '11');
INSERT INTO synonymset VALUES ('precisely', '5376');
INSERT INTO synonymset VALUES ('smooth ground somebody', '1827');
INSERT INTO synonymset VALUES ('strong caref', '3898');
INSERT INTO synonymset VALUES ('jer', '4224');
INSERT INTO synonymset VALUES ('knew talk br', '3651');
INSERT INTO synonymset VALUES ('grimly set coast strain', '5272');
INSERT INTO synonymset VALUES ('ple', '4498');
INSERT INTO synonymset VALUES ('waste behalf friar', '2967');
INSERT INTO synonymset VALUES ('kenti', '2903');
INSERT INTO synonymset VALUES ('wrath strangely c', '410');
